version: 2.1

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: kitman20022002/techscrumapp
    docker:
      - image: circleci/node:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
jobs:
  dast:
    docker:
      - image: cimg/node:16.17.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}
  dscan:
    docker:
      - image: cimg/node:16.17.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}
  sast:
    docker:
      - image: cimg/node:16.17.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run lint
      # sonarcloud/scan step removed due to orb loading error
  unit_test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Check commit message
          command: |
            if git log --pretty=format:"%s" -n 1 | grep -q "[skip ci]"; then
              echo "Commit message indicates to skip CI. Exiting."
              circleci-agent step halt
            fi
  skip_ci_check:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Check commit message
          command: |
            if git log --pretty=format:"%s" -n 1 | grep -q "[skip ci]"; then
              echo "Commit message indicates to skip CI. Exiting."
              circleci-agent step halt
            fi
  semantic_release:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Check commit message
          command: |
            if git log --pretty=format:"%s" -n 1 | grep -q "[skip ci]"; then
              echo "Commit message indicates to skip CI. Exiting."
              circleci-agent step halt
            fi
  integration_test:
    docker:
      - image: cimg/node:16.17.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
workflows:
  server_deploy:
    jobs:
      - skip_ci_check
      - dscan:
          requires:
            - skip_ci_check
      - dast:
          requires:
            - skip_ci_check
      - sast:
          requires:
            - skip_ci_check
      - unit_test:
          requires:
            - skip_ci_check
      - integration_test:
          requires:
            - skip_ci_check
      - semantic_release:
          requires:
            - sast
            - dast
            - dscan
            - integration_test
            - unit_test
          filters:
            branches:
              only:
                - master
